/** User journeys against the compiled Braven Studio, with real rig and storage checks. */
import { createRequire } from 'node:module'
import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'
const require=createRequire(path.join(process.env.BRAVEN_TACTICS_PATH||'F:/Repositories/braven-tactics-netball-athlete','package.json'))
const puppeteer=require('puppeteer-core')
const out=path.resolve('verification/studio');fs.mkdirSync(out,{recursive:true})
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,defaultViewport:{width:1440,height:1000}})
const page=await browser.newPage(),errors=[],checks=[]
const url=process.env.STUDIO_URL||'http://127.0.0.1:5397/'
const check=(name,value)=>{assert(value,name);checks.push(name)}
const input=async(selector,value)=>page.$eval(selector,(el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))},value)
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms))
const ready=async p=>{await p.goto(url,{waitUntil:'networkidle0'});await p.waitForFunction(()=>!!window.bravenStudio)}
const shot=async name=>page.screenshot({path:path.join(out,name+'.png'),fullPage:true})
page.on('pageerror',error=>errors.push(String(error)))
const cdp=await page.createCDPSession();await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:out})
try{
  await ready(page)
  check('Compiled app loads the real model, two kits and all 17 clips',await page.evaluate(()=>window.bravenStudio.catalog.animations.length===17&&window.bravenStudio.catalog.kits.length===2&&window.athleteStudio.bones.size===70))
  check('Initial app fits desktop width',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
  await shot('desktop')
  await page.type('#library-search','jump');await page.select('#category','Catching')
  check('Search and category filter combine in the visible library',await page.$$eval('[data-animation]',els=>els.length===1&&els[0].textContent.includes('Jump catch')))
  await page.click('[data-animation="netball_hooks_jump_pull_in"]');await page.click('#play')
  check('Choosing a library animation changes the actual model action',await page.evaluate(()=>window.athleteStudio.state.clip==='netball_hooks_jump_pull_in'))
  await page.click('[data-tab="review"]')
  check('Source review needs are visible without claiming coach approval',await page.$eval('#review-description',el=>el.textContent.includes('not been coach-approved')&&el.textContent.includes('need review')))
  await input('#library-search','no such movement');check('Empty search has a useful recovery message',await page.$eval('#library-results',el=>el.textContent.includes('No matching animations')))
  await input('#library-search','');await page.select('#category','All');await page.click('[data-animation="netball_chest_pass"]');await page.click('#play')
  await page.click('#phase-buttons button[data-time="1.1666666666666667"]').catch(async()=>{
    const phase=await page.$$('#phase-buttons button');await phase[Math.min(3,phase.length-1)].click()
  })
  const moment=await page.evaluate(()=>window.athleteStudio.state.time)
  await page.click('#step-forward')
  check('Frame stepping advances one 60 fps frame while paused',await page.evaluate(t=>Math.abs(window.athleteStudio.state.time-t-1/60)<1e-6&&!window.athleteStudio.state.playing,moment))
  await page.click('#restart');check('Restart returns to the beginning',await page.evaluate(()=>window.athleteStudio.state.time===0))
  await page.click('#play');await wait(300);await page.click('#play')
  check('The real Play control advances the timeline',await page.evaluate(()=>window.athleteStudio.state.time>.15&&!window.athleteStudio.state.playing))
  // Every clip is driven through the UI; measure actual joint movement at two times.
  const movements=[]
  for(const clip of await page.evaluate(()=>window.athleteStudio.clips.map(c=>({name:c.name,duration:c.duration})))){
    await page.select('#clip',clip.name);await input('#timeline',.02)
    const before=await page.evaluate(()=>[...window.athleteStudio.bones.values()].flatMap(b=>[...b.quaternion.toArray(),...b.position.toArray()]))
    await input('#timeline',clip.duration*.72)
    const difference=await page.evaluate(before=>Math.max(...[...window.athleteStudio.bones.values()].flatMap(b=>[...b.quaternion.toArray(),...b.position.toArray()]).map((n,i)=>Math.abs(n-before[i]))),before)
    check(`${clip.name} animates rig joints`,difference>1e-4);movements.push({clip:clip.name,difference})
  }
  await page.click('[data-section="kits"]');await page.click('[data-library-kit="shorts"]')
  check('Kit card switches the actual skirt mesh off',await page.evaluate(()=>!window.athleteStudio.model.getObjectByName('Kit_Skirt').visible))
  await input('#primary','#9a3157');await input('#height','1.81')
  await shot('kits')
  await page.click('[data-tab="animate"]');await page.select('#clip','netball_chest_pass');await input('#timeline',.6)
  await page.click('[data-tab="pose"]');await page.select('#bone','lowerarm_l');await input('#rx','20')
  const pose=await page.evaluate(()=>window.athleteStudio.bones.get('lowerarm_l').quaternion.toArray())
  await page.click('[data-tab="review"]');await page.type('#review-note','Check the left wrist at release.')
  await page.click('#save-setup');await input('#setup-name','Wrist and shorts review');await page.click('#save-form [type="submit"]')
  check('Named setup is saved with the edited pose and review note',await page.evaluate(()=>window.bravenStudio.workspace.saved[0].note==='Check the left wrist at release.'&&!!window.bravenStudio.workspace.saved[0].setup.pose))
  await page.reload({waitUntil:'networkidle0'});await page.waitForFunction(()=>window.bravenStudio)
  check('Kit, height and edited pose survive reload',await page.evaluate(expected=>{
    const app=window.athleteStudio;return app.state.kit==='shorts'&&app.state.height===1.81&&app.state.poseMode&&app.bones.get('lowerarm_l').quaternion.toArray().every((n,i)=>Math.abs(n-expected[i])<1e-8)
  },pose))
  await page.click('[data-section="saved"]');check('Saved library retains notes after reload',await page.$eval('#library-results',el=>el.textContent.includes('Wrist and shorts review')&&el.textContent.includes('Check the left wrist')))
  await page.click('[data-saved]');await shot('saved-pose')
  await page.click('#export-workspace');await page.waitForFunction(()=>document.getElementById('notification-text').textContent.includes('exported'))
  const exported=path.join(out,'braven-studio-workspace.json');for(let i=0;i<30&&!fs.existsSync(exported);i++)await wait(100)
  check('Export contains the saved review and pose',JSON.parse(fs.readFileSync(exported,'utf8')).saved[0].setup.pose.lowerarm_l!==undefined)
  await page.click('.delete-setup');check('Remove changes the saved list',await page.evaluate(()=>window.bravenStudio.workspace.saved.length===0))
  await page.click('#undo-delete');check('Undo restores the saved setup',await page.evaluate(()=>window.bravenStudio.workspace.saved.length===1))
  const invalid=path.join(out,'invalid-workspace.json');const bad=JSON.parse(fs.readFileSync(exported,'utf8'));bad.assetHash='0'.repeat(64);fs.writeFileSync(invalid,JSON.stringify(bad))
  await (await page.$('#workspace-file')).uploadFile(invalid)
  await page.waitForFunction(()=>document.getElementById('notification').classList.contains('error'))
  check('Incompatible import leaves existing saved work intact',await page.evaluate(()=>window.bravenStudio.workspace.saved.length===1&&document.getElementById('notification-text').textContent.includes('different model')))
  await page.click('#close-notification')
  const context=await browser.createBrowserContext();const importedPage=await context.newPage();await ready(importedPage)
  await (await importedPage.$('#workspace-file')).uploadFile(exported);await importedPage.waitForFunction(()=>window.bravenStudio.workspace.saved.length===1)
  check('Exported workspace restores in a fresh browser context',await importedPage.evaluate(()=>window.athleteStudio.state.poseMode&&window.athleteStudio.state.kit==='shorts'&&document.getElementById('review-note').value.includes('left wrist')))
  await context.close()
  const errorContext=await browser.createBrowserContext();const errorPage=await errorContext.newPage();await ready(errorPage)
  await errorPage.evaluate(()=>{window.originalStorageWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('Storage full')}})
  await errorPage.click('#save-setup');await errorPage.click('#save-form [type="submit"]')
  check('Storage failure appears inside the save dialog without claiming success',await errorPage.$eval('#save-error',el=>!el.hidden&&el.textContent.includes('Could not save'))&&await errorPage.evaluate(()=>window.bravenStudio.workspace.saved.length===0))
  await errorContext.close()
  const recoveryContext=await browser.createBrowserContext();const recoveryPage=await recoveryContext.newPage()
  const asset=await page.evaluate(()=>window.bravenStudio.catalog.assetHash)
  await recoveryPage.evaluateOnNewDocument(hash=>localStorage.setItem(`braven-studio.workspace.v1.${hash}`,'{broken'),asset)
  await ready(recoveryPage)
  check('Corrupt browser data has a recovery copy and a visible message',await recoveryPage.evaluate(hash=>localStorage.getItem(`braven-studio.workspace.v1.${hash}.recovery`)==='{broken'&&document.getElementById('notification-text').textContent.includes('recovery copy'),asset))
  await recoveryContext.close()
  await page.click('[data-section="models"]');check('Models library contains the real available model revision',await page.evaluate(async()=>{
    const manifest=await(await fetch('/athlete-assets/manifest.json')).json(),text=document.getElementById('library-results').textContent
    return text.includes('Netball athlete')&&text.includes(`Revision ${manifest.revision}`)
  }))
  await page.click('#model-card');await page.click('[data-tab="animate"]');await page.select('#driver','tactics')
  check('Tactics driver remains connected',await page.evaluate(()=>window.athleteStudio.rig.authored&&window.athleteStudio.state.driver==='tactics'&&window.athleteStudio.rig.group.parent.visible))
  await input('#timeline',3);await page.click('[data-tab="pose"]');await page.click('#save-setup');await input('#setup-name','Pose after Tactics preview');await page.click('#save-form [type="submit"]')
  check('A pose opened late in the Tactics cycle can be saved against the shorter native clip',await page.evaluate(()=>window.bravenStudio.workspace.saved.length===2))
  await page.click('[data-tab="animate"]')
  await page.select('#driver','clips');await page.select('#clip','netball_chest_pass');await input('#timeline',.6)
  await page.click('#capture-frame');await wait(200)
  check('Frame capture produces a real PNG',fs.readdirSync(out).some(name=>name.endsWith('.png')&&name.startsWith('braven-netball_chest_pass-')))
  await page.setViewport({width:390,height:844});await page.click('[data-section="animations"]')
  check('Mobile has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
  await page.click('[data-animation="netball_chest_pass"]');await page.click('#play');await shot('mobile')
  check('Mobile library selection returns to the visible preview',await page.$eval('#stage',el=>{const r=el.getBoundingClientRect();return r.top>=-5&&r.top<100}))
  check('No application exceptions',errors.length===0)
  const receipt=await page.evaluate(async()=>await (await fetch('/studio-build.json')).json())
  fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify({url,receipt,checks,movements,errors},null,2))
  console.log(JSON.stringify({passed:checks.length,buildId:receipt.buildId,errors},null,2))
}catch(error){fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({checks,errors,error:String(error)},null,2));await shot('failure').catch(()=>{});throw error}
finally{const timer=setTimeout(()=>browser.process()?.kill(),5000);try{await browser.close()}finally{clearTimeout(timer)}}
